Ale dc27
Yerola/pf-ecommerce-gaming pull request #1
Opened 2023-04-20 19:50 UTC by AleDC27

testeo de como usar branch

2023-04-20 22:55 UTC, Yerola approved these changes
Copada la prueba. Tienes mi aprobación.

2023-04-20 22:56 UTC, Yerola commented
Falta que apruebe alguien más... pero tiene buena pinta jejejeje

2023-04-21 00:08 UTC, LeoHeffel requested changes
no me corre tu codigo. podes explicar que hace?

2023-04-21 12:30 UTC, DarioFunes89 approved these changes
creo q esta bien

2023-04-21 12:52 UTC, LeoHeffel approved these changes

2023-04-21 14:12 UTC, claudiop1975 commented on text.txt
> +Test file
OK, i´m trying to understan so complex code, trying to implement some kinda test, but i trust r expertise. i Thin it's OK

2023-04-21 14:20 UTC, claudiop1975 requested changes
May be you can change a little, like 
const fn=(ok) => {
  if (ok) {
    console.log('Check Approve, with the text "OK"');
  }else {console.log('Refactoring time!!')}
}

2023-04-21 18:29 UTC, closed without merging